[theme]
primaryColor = "#4CAF50"
backgroundColor = "#0f1115"
secondaryBackgroundColor = "#1c1f27"
textColor = "#FFFFFF"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
enableXsrfProtection = false
enableCORS = false
enableWebsocketCompression = true

[client]
showErrorDetails = false
toolbarMode = "minimal"
